import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

import OccriLogo from 'assets/brand/occri-logo.svg'

import { InitialCarousel } from './components/initial-carousel'

import { Spaces } from './components/spaces'
import { Events } from './components/events'
import { EventsAdvert } from './components/events-advert'
import { Footer } from '../../components/footer'
import { About } from './components/about'

import styles from './styles.module.scss'

const Home: NextPage = () => {

  return (
    <div className={styles.container}>
      <Head>
        <title>Occri</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>  
        <div className={styles.logo}>
          <div className={styles['logo__content']}>
            <Image src={OccriLogo} alt='Occri logo'/>
          </div>
        </div>
        <div className={styles.sliders}>
          <div className={styles['sliders__content']}>
            <InitialCarousel />
          </div>
        </div>
        <Spaces />
        <Events />
        <EventsAdvert/>
        <About />
      </main>
      <Footer />
    </div>
  )
}

export default Home
