import { useEffect } from 'react'

import type { NextPage as INextPage} from 'next'
import Head from 'next/head'
import Image from 'next/image'

import OccriLogo from 'assets/brand/occri-logo.svg'
import { Footer } from 'components/footer'

import { HomeBanner } from './components/home-banner'
import { Spaces } from './components/spaces'
import { Events } from './components/events'
import { EventsAdvert } from './components/events-advert'
import { About } from './components/about'

import styles from './styles.module.scss'

const Home: INextPage = () => {
  useEffect(() =>  {document.body.classList.add(styles['body-container'])}, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Occri</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>  
        <div className={styles.logo}>
          <div className={styles['logo__content']}>
            <a href='/'>
              <Image src={OccriLogo} alt='Occri logo' />
            </a>
          </div>
        </div>
        <HomeBanner />
        <Spaces />
        <Events />
        <EventsAdvert/>
        <About />
      </main>
      <Footer />
    </div>
  )
}

export default Home
