import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

import { Carousel } from '@/components/carousel'

import styles from './styles.module.scss'
import { PlaceCard } from '@/components/place-card'

const places = [ 
  {
    id: 1,
    name: 'Reunião Grande',
    img: 'imagem',
    description: 'Sala de reunião  preparadas  para receber apresentações.',
  },
  {
    id: 2,
    name: 'Sala verde',
    img: 'imagem',
    description: 'Sala de reunião  preparadas  para receber apresentações.',
  },
  {
    id: 3,
    name: 'Espaço Kids',
    img: 'imagem',
    description: 'Sala de reunião  preparadas  para receber apresentações.',
  },
  {
    id: 4,
    name: 'Estúdio de Gravação',
    img: 'imagem',
    description: 'Sala de reunião  preparadas  para receber apresentações.',
  },
  {
    id: 5,
    name: 'Better together',
    img: 'imagem',
    description: 'Sala de reunião  preparadas  para receber apresentações.',
  }
]

const Home: NextPage = () => {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>  
        <div className={styles.logo}>

        </div>
        {/* <OwlCarousel
          dots={false}
          loop
        >
          <div className={styles.card}>teste</div>
        </OwlCarousel> */}
        <div className={styles.places}>
          <h2>Nossos espaços</h2>
            <Carousel
              dots={false}
              nav={false}
              autoplay={false}
              autoplayTimeout={2000}
              autoplaySpeed={2000}
              autoplayHoverPause={false}
              margin={60}
              autoWidth
            >
              {places.map(place => (
                <PlaceCard 
                  key={place.id}
                  name={place.name}
                  img={place.img}
                  description={place.description}
                />
              ))}
            </Carousel>
        </div>
        <div className={styles.events}>
          <h2>Próximos eventos</h2>
        </div>
        <div className={styles.about}>
          <h2>Sobre nós</h2>

        </div>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

export default Home
