import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

import { Carousel } from '@/components/carousel'

import styles from './styles.module.scss'
import { PlaceCard } from './components/place-card'
import { EventCard } from './components/event-card'
import { SliderCard } from './components/slider-card'

const places = [ 
  {
    id: 1,
    name: 'Reunião Grande',
    img: 'imagem',
    description: 'Sala de reunião  preparadas  para receber apresentações.',
  },
  {
    id: 2,
    name: 'Sala verde',
    img: 'imagem',
    description: 'Sala de reunião  preparadas  para receber apresentações.',
  },
  {
    id: 3,
    name: 'Espaço Kids',
    img: 'imagem',
    description: 'Sala de reunião  preparadas  para receber apresentações.',
  },
  {
    id: 4,
    name: 'Estúdio de Gravação',
    img: 'imagem',
    description: 'Sala de reunião  preparadas  para receber apresentações.',
  },
  {
    id: 5,
    name: 'Better together',
    img: 'imagem',
    description: 'Sala de reunião  preparadas  para receber apresentações.',
  }
]

const events = [ 
  {
    id: 1,
    name: 'Reunião Grande',
    img: 'imagem',
    description: 'Sala de reunião  preparadas  para receber apresentações.',
  },
  {
    id: 2,
    name: 'Sala verde',
    img: 'imagem',
    description: 'Sala de reunião  preparadas  para receber apresentações.',
  },
  {
    id: 3,
    name: 'Espaço Kids',
    img: 'imagem',
    description: 'Sala de reunião  preparadas  para receber apresentações.',
  },
  {
    id: 4,
    name: 'Estúdio de Gravação',
    img: 'imagem',
    description: 'Sala de reunião  preparadas  para receber apresentações.',
  },
  {
    id: 5,
    name: 'Better together',
    img: 'imagem',
    description: 'Sala de reunião  preparadas  para receber apresentações.',
  }
]

const sliders = [ 
  {
    id: 1,
    img: 'imagem',
  },
  {
    id: 2,
    img: 'imagem',
  },
  {
    id: 3,
    img: 'imagem',
  },
  {
    id: 4,
    img: 'imagem',
  },
  {
    id: 5,
    img: 'imagem',
  }
]

const Home: NextPage = () => {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>  
        <div className={styles.logo}>

        </div>
        <div className={styles.sliders}>
          <Carousel
            animateOut= 'slideOutDown'
            animateIn= 'flipInX'
            items={1}
            dots={false}
            autoplay={false}
            autoplayTimeout={2000}
            autoplaySpeed={2000}
            autoplayHoverPause={false}
          >
            {sliders.map(slider => (
              <SliderCard 
                key={slider.id}
                img={slider.img}
              />
            ))}
          </Carousel>
        </div>
        <div className={styles.places}>
          <h2>Nossos espaços</h2>
            <Carousel
              dots={false}
              nav={false}
              autoplay={false}
              autoplayTimeout={2000}
              autoplaySpeed={2000}
              autoplayHoverPause={false}
              margin={60}
              autoWidth
            >
              {places.map(place => (
                <PlaceCard 
                  key={place.id}
                  name={place.name}
                  img={place.img}
                  description={place.description}
                />
              ))}
            </Carousel>
        </div>
        <div className={styles.events}>
          <h2>Próximos eventos</h2>
          <div className={styles['events__container']}>
            <div className={styles['events__container__description']}>
              <h1>Evento teste</h1>
              <p> 
                Espaços preparados para receber seu evento da melhor maneira possivel, 
                possuimos bar, restaurante, espaço KIDS e toda uma estrutura pronta para receber 
                você e suas colegas de trabalho!
              </p>
            </div>
            <div className={styles['events__container__carousel']}>
              <Carousel
                animateOut= 'slideOutDown'
                animateIn= 'flipInX'
                items={1}
                dots={false}
                nav={true}
                autoplay={false}
                autoplayTimeout={2000}
                autoplaySpeed={2000}
                autoplayHoverPause={false}
                navClass={['navigation-previous', 'navigation-next']}
              >
                {events.map(event => (
                  <EventCard 
                    key={event.id}
                    img={event.img}
                  />
                ))}
              </Carousel>
            </div>
          </div>
        </div>
        <div className={styles.about}>
          <h2>Sobre nós</h2>

        </div>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

export default Home
