import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

import OccriLogo from 'assets/brand/occri-logo.svg'
import OccriCompleteLogo from 'assets/brand/occri-complete-logo.svg'

import { InitialCarousel } from './components/initial-carousel'
import { SpaceCarousel } from './components/space-carousel'
import { EventCarousel } from './components/event-carousel'
import { Footer } from './components/footer'

import styles from './styles.module.scss'

const Home: NextPage = () => {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>  
        <div className={styles.logo}>
          <Image src={OccriLogo} alt='Occri logo'/>
        </div>
        <div className={styles.sliders}>
          <InitialCarousel />
        </div>
        <div className={styles.spaces}>
          <h2>Nossos espaços</h2>
            <SpaceCarousel />
        </div>
        <div className={styles.events}>
          <h2>Próximos eventos</h2>
          <div className={styles['events__container']}>
            <div className={styles['events__container__description']}>
              <h1>Evento teste</h1>
              <p> 
                Espaços preparados para receber seu evento da melhor maneira possivel, 
                possuimos bar, restaurante, espaço KIDS e toda uma estrutura pronta para receber 
                você e suas colegas de trabalho!
              </p>
            </div>
            <div className={styles['events__container__carousel']}>
              <EventCarousel />
            </div>
          </div>
          <div className={styles['events__advert']}>
            <div className={styles['events__advert__content']}>
              <h2>Faça seu evento conosco!</h2>
              <p>
                Espaços preparados para receber seu evento da melhor maneira possivel, possuimos bar, restaurante, espaço KIDS e toda uma estrutura pronta para receber você e suas colegas de trabalho!
              </p>
            </div>
            <div className={styles['events__advert__button']}>
              <button>
                Datas disponiveis
              </button>
            </div>
          </div>
        </div>
        <div className={styles.about}>
          <div className={styles['about__content']}>
            <h2>Sobre nós</h2>
            <h3>Olá, somos a OCCRI</h3>
            <p>
            Mais do que um espaço compartilhado, a Occri é um complexo totalmente pensado e elaborado para criar uma experiencia única e diferenciada, contanto com diversos setores dentro do mesmo local: bar, restaurante, espaço kids, área de eventos e muito mais. Tem como propósito empoderar mulheres a serem protagonistas das suas próprias histórias, criando um ambiente acolhedor e possibilitador.
            </p>
          </div>
          <div>
            <Image src={OccriCompleteLogo} alt="Logo completo com texto coworking multissetorial feminino" />
          </div>
        </div>
      </main>
      <Footer />
    </div>
  )
}

export default Home
