import { useEffect, useState, useCallback } from 'react'
import { HiOutlineUserGroup } from 'react-icons/hi'

import type { NextPage as INextPage } from 'next'
import { useRouter } from 'next/router'
import Head from 'next/head'
import Image from 'next/image'

import OccriLogo from 'assets/brand/occri-logo.svg'
import { Footer } from 'components/footer'
import { spacesApi } from 'pages/api'

import { Spaces } from './components/spaces'
import styles from './styles.module.scss'

interface ISpace {
  uuid: string,
  name: string,
  description: string,
  quantity: number,
}

const Details: INextPage = () => {
  const [ space, setSpace ] = useState<ISpace | undefined>(undefined);

  const router = useRouter();
  const { id } = router?.query;

  const redirectToHome = useCallback(
    () => {
      router.push('/');
    },
    [router],
  )

  useEffect(() => { document.body.classList.add(styles['body-container']);  }, []);
  useEffect(() => { 
    if(id === undefined) {
      return
    }
    const fetchSpace = async () => {
      try {
        const response: ISpace = await spacesApi.getSpace(id as string)

        if(response) {
          setSpace(response)
        }

      } catch(error) {
        redirectToHome();
      };
    }
      
    fetchSpace();
  }, [id, setSpace, redirectToHome]);

  console.log(space)

  return (
    <div className={styles.container}>
      <Head>
        <title>Occri</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>  
        <div className={styles.logo}>
          <div className={styles['logo__content']}>
            <a href='/'>
              <Image src={OccriLogo} alt='Occri logo'/>
            </a>
          </div>
        </div>
        <div className={styles.details}>
            <div className={styles['details__content']}>
                <h2>Reserva </h2>
                <div className={styles['details__content__carousel']}>
                  {/* carousel or image */}
                </div>
                <div className={styles['details__content__description']}>
                  <h1>{space?.name}</h1>
                  <p>{space?.description}</p>
                  <div className={styles['details__content__description__quantity']}>
                    <div className={styles['details__content__description__quantity__icon']}>
                        <HiOutlineUserGroup/> 
                    </div>
                    {space?.quantity}
                  </div>
                </div>
            </div>
        </div>
        <Spaces />
      </main>
      <Footer />
    </div>
  )
}

export default Details
