import type { NextPage as INextPage } from "next";
import Head from "next/head";
import { useEffect } from "react";

import { Footer } from "components/footer";

import styles from "./styles.module.scss";

const Home: INextPage = () => {
	useEffect(() => { document.body.classList.add(styles["body-container"]); }, []);

	return (
		<div className={styles.container}>
			<Head>
				<title>Example</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<div />
			</main>
			<Footer />
		</div>
	);
};

export default Home;
